/*
Snap Conversions API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package businesssdk

import (
	"encoding/json"
)

// CapiEvent struct for CapiEvent
type CapiEvent struct {
	PixelId *string `json:"pixel_id,omitempty"`
	AppId *string `json:"app_id,omitempty"`
	SnapAppId *string `json:"snap_app_id,omitempty"`
	EventType *string `json:"event_type,omitempty"`
	EventConversionType *string `json:"event_conversion_type,omitempty"`
	EventTag *string `json:"event_tag,omitempty"`
	Timestamp *string `json:"timestamp,omitempty"`
	HashedEmail *string `json:"hashed_email,omitempty"`
	HashedMobileAdId *string `json:"hashed_mobile_ad_id,omitempty"`
	UuidC1 *string `json:"uuid_c1,omitempty"`
	HashedIdfv *string `json:"hashed_idfv,omitempty"`
	HashedPhoneNumber *string `json:"hashed_phone_number,omitempty"`
	UserAgent *string `json:"user_agent,omitempty"`
	HashedIpAddress *string `json:"hashed_ip_address,omitempty"`
	ItemCategory *string `json:"item_category,omitempty"`
	ItemIds *string `json:"item_ids,omitempty"`
	Description *string `json:"description,omitempty"`
	NumberItems *string `json:"number_items,omitempty"`
	Price *string `json:"price,omitempty"`
	Currency *string `json:"currency,omitempty"`
	TransactionId *string `json:"transaction_id,omitempty"`
	Level *string `json:"level,omitempty"`
	ClientDedupId *string `json:"client_dedup_id,omitempty"`
	DataUse *string `json:"data_use,omitempty"`
	SearchString *string `json:"search_string,omitempty"`
	PageUrl *string `json:"page_url,omitempty"`
	SignUpMethod *string `json:"sign_up_method,omitempty"`
	HashedFirstNameSha *string `json:"hashed_first_name_sha,omitempty"`
	HashedFirstNameSdx *string `json:"hashed_first_name_sdx,omitempty"`
	HashedMiddleNameSha *string `json:"hashed_middle_name_sha,omitempty"`
	HashedMiddleNameSdx *string `json:"hashed_middle_name_sdx,omitempty"`
	HashedLastNameSha *string `json:"hashed_last_name_sha,omitempty"`
	HashedLastNameSdx *string `json:"hashed_last_name_sdx,omitempty"`
	HashedCitySha *string `json:"hashed_city_sha,omitempty"`
	HashedCitySdx *string `json:"hashed_city_sdx,omitempty"`
	HashedStateSha *string `json:"hashed_state_sha,omitempty"`
	HashedStateSdx *string `json:"hashed_state_sdx,omitempty"`
	HashedZip *string `json:"hashed_zip,omitempty"`
	HashedDobMonth *string `json:"hashed_dob_month,omitempty"`
	HashedDobDay *string `json:"hashed_dob_day,omitempty"`
	Integration *string `json:"integration,omitempty"`
	ClickId *string `json:"click_id,omitempty"`
}

// NewCapiEvent instantiates a new CapiEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCapiEvent() *CapiEvent {
	this := CapiEvent{}
	return &this
}

// NewCapiEventWithDefaults instantiates a new CapiEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCapiEventWithDefaults() *CapiEvent {
	this := CapiEvent{}
	return &this
}

// GetPixelId returns the PixelId field value if set, zero value otherwise.
func (o *CapiEvent) GetPixelId() string {
	if o == nil || o.PixelId == nil {
		var ret string
		return ret
	}
	return *o.PixelId
}

// GetPixelIdOk returns a tuple with the PixelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetPixelIdOk() (*string, bool) {
	if o == nil || o.PixelId == nil {
		return nil, false
	}
	return o.PixelId, true
}

// HasPixelId returns a boolean if a field has been set.
func (o *CapiEvent) HasPixelId() bool {
	if o != nil && o.PixelId != nil {
		return true
	}

	return false
}

// SetPixelId gets a reference to the given string and assigns it to the PixelId field.
func (o *CapiEvent) SetPixelId(v string) {
	o.PixelId = &v
}

// GetAppId returns the AppId field value if set, zero value otherwise.
func (o *CapiEvent) GetAppId() string {
	if o == nil || o.AppId == nil {
		var ret string
		return ret
	}
	return *o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetAppIdOk() (*string, bool) {
	if o == nil || o.AppId == nil {
		return nil, false
	}
	return o.AppId, true
}

// HasAppId returns a boolean if a field has been set.
func (o *CapiEvent) HasAppId() bool {
	if o != nil && o.AppId != nil {
		return true
	}

	return false
}

// SetAppId gets a reference to the given string and assigns it to the AppId field.
func (o *CapiEvent) SetAppId(v string) {
	o.AppId = &v
}

// GetSnapAppId returns the SnapAppId field value if set, zero value otherwise.
func (o *CapiEvent) GetSnapAppId() string {
	if o == nil || o.SnapAppId == nil {
		var ret string
		return ret
	}
	return *o.SnapAppId
}

// GetSnapAppIdOk returns a tuple with the SnapAppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetSnapAppIdOk() (*string, bool) {
	if o == nil || o.SnapAppId == nil {
		return nil, false
	}
	return o.SnapAppId, true
}

// HasSnapAppId returns a boolean if a field has been set.
func (o *CapiEvent) HasSnapAppId() bool {
	if o != nil && o.SnapAppId != nil {
		return true
	}

	return false
}

// SetSnapAppId gets a reference to the given string and assigns it to the SnapAppId field.
func (o *CapiEvent) SetSnapAppId(v string) {
	o.SnapAppId = &v
}

// GetEventType returns the EventType field value if set, zero value otherwise.
func (o *CapiEvent) GetEventType() string {
	if o == nil || o.EventType == nil {
		var ret string
		return ret
	}
	return *o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetEventTypeOk() (*string, bool) {
	if o == nil || o.EventType == nil {
		return nil, false
	}
	return o.EventType, true
}

// HasEventType returns a boolean if a field has been set.
func (o *CapiEvent) HasEventType() bool {
	if o != nil && o.EventType != nil {
		return true
	}

	return false
}

// SetEventType gets a reference to the given string and assigns it to the EventType field.
func (o *CapiEvent) SetEventType(v string) {
	o.EventType = &v
}

// GetEventConversionType returns the EventConversionType field value if set, zero value otherwise.
func (o *CapiEvent) GetEventConversionType() string {
	if o == nil || o.EventConversionType == nil {
		var ret string
		return ret
	}
	return *o.EventConversionType
}

// GetEventConversionTypeOk returns a tuple with the EventConversionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetEventConversionTypeOk() (*string, bool) {
	if o == nil || o.EventConversionType == nil {
		return nil, false
	}
	return o.EventConversionType, true
}

// HasEventConversionType returns a boolean if a field has been set.
func (o *CapiEvent) HasEventConversionType() bool {
	if o != nil && o.EventConversionType != nil {
		return true
	}

	return false
}

// SetEventConversionType gets a reference to the given string and assigns it to the EventConversionType field.
func (o *CapiEvent) SetEventConversionType(v string) {
	o.EventConversionType = &v
}

// GetEventTag returns the EventTag field value if set, zero value otherwise.
func (o *CapiEvent) GetEventTag() string {
	if o == nil || o.EventTag == nil {
		var ret string
		return ret
	}
	return *o.EventTag
}

// GetEventTagOk returns a tuple with the EventTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetEventTagOk() (*string, bool) {
	if o == nil || o.EventTag == nil {
		return nil, false
	}
	return o.EventTag, true
}

// HasEventTag returns a boolean if a field has been set.
func (o *CapiEvent) HasEventTag() bool {
	if o != nil && o.EventTag != nil {
		return true
	}

	return false
}

// SetEventTag gets a reference to the given string and assigns it to the EventTag field.
func (o *CapiEvent) SetEventTag(v string) {
	o.EventTag = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *CapiEvent) GetTimestamp() string {
	if o == nil || o.Timestamp == nil {
		var ret string
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetTimestampOk() (*string, bool) {
	if o == nil || o.Timestamp == nil {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *CapiEvent) HasTimestamp() bool {
	if o != nil && o.Timestamp != nil {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given string and assigns it to the Timestamp field.
func (o *CapiEvent) SetTimestamp(v string) {
	o.Timestamp = &v
}

// GetHashedEmail returns the HashedEmail field value if set, zero value otherwise.
func (o *CapiEvent) GetHashedEmail() string {
	if o == nil || o.HashedEmail == nil {
		var ret string
		return ret
	}
	return *o.HashedEmail
}

// GetHashedEmailOk returns a tuple with the HashedEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetHashedEmailOk() (*string, bool) {
	if o == nil || o.HashedEmail == nil {
		return nil, false
	}
	return o.HashedEmail, true
}

// HasHashedEmail returns a boolean if a field has been set.
func (o *CapiEvent) HasHashedEmail() bool {
	if o != nil && o.HashedEmail != nil {
		return true
	}

	return false
}

// SetHashedEmail gets a reference to the given string and assigns it to the HashedEmail field.
func (o *CapiEvent) SetHashedEmail(v string) {
	o.HashedEmail = &v
}

// GetHashedMobileAdId returns the HashedMobileAdId field value if set, zero value otherwise.
func (o *CapiEvent) GetHashedMobileAdId() string {
	if o == nil || o.HashedMobileAdId == nil {
		var ret string
		return ret
	}
	return *o.HashedMobileAdId
}

// GetHashedMobileAdIdOk returns a tuple with the HashedMobileAdId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetHashedMobileAdIdOk() (*string, bool) {
	if o == nil || o.HashedMobileAdId == nil {
		return nil, false
	}
	return o.HashedMobileAdId, true
}

// HasHashedMobileAdId returns a boolean if a field has been set.
func (o *CapiEvent) HasHashedMobileAdId() bool {
	if o != nil && o.HashedMobileAdId != nil {
		return true
	}

	return false
}

// SetHashedMobileAdId gets a reference to the given string and assigns it to the HashedMobileAdId field.
func (o *CapiEvent) SetHashedMobileAdId(v string) {
	o.HashedMobileAdId = &v
}

// GetUuidC1 returns the UuidC1 field value if set, zero value otherwise.
func (o *CapiEvent) GetUuidC1() string {
	if o == nil || o.UuidC1 == nil {
		var ret string
		return ret
	}
	return *o.UuidC1
}

// GetUuidC1Ok returns a tuple with the UuidC1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetUuidC1Ok() (*string, bool) {
	if o == nil || o.UuidC1 == nil {
		return nil, false
	}
	return o.UuidC1, true
}

// HasUuidC1 returns a boolean if a field has been set.
func (o *CapiEvent) HasUuidC1() bool {
	if o != nil && o.UuidC1 != nil {
		return true
	}

	return false
}

// SetUuidC1 gets a reference to the given string and assigns it to the UuidC1 field.
func (o *CapiEvent) SetUuidC1(v string) {
	o.UuidC1 = &v
}

// GetHashedIdfv returns the HashedIdfv field value if set, zero value otherwise.
func (o *CapiEvent) GetHashedIdfv() string {
	if o == nil || o.HashedIdfv == nil {
		var ret string
		return ret
	}
	return *o.HashedIdfv
}

// GetHashedIdfvOk returns a tuple with the HashedIdfv field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetHashedIdfvOk() (*string, bool) {
	if o == nil || o.HashedIdfv == nil {
		return nil, false
	}
	return o.HashedIdfv, true
}

// HasHashedIdfv returns a boolean if a field has been set.
func (o *CapiEvent) HasHashedIdfv() bool {
	if o != nil && o.HashedIdfv != nil {
		return true
	}

	return false
}

// SetHashedIdfv gets a reference to the given string and assigns it to the HashedIdfv field.
func (o *CapiEvent) SetHashedIdfv(v string) {
	o.HashedIdfv = &v
}

// GetHashedPhoneNumber returns the HashedPhoneNumber field value if set, zero value otherwise.
func (o *CapiEvent) GetHashedPhoneNumber() string {
	if o == nil || o.HashedPhoneNumber == nil {
		var ret string
		return ret
	}
	return *o.HashedPhoneNumber
}

// GetHashedPhoneNumberOk returns a tuple with the HashedPhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetHashedPhoneNumberOk() (*string, bool) {
	if o == nil || o.HashedPhoneNumber == nil {
		return nil, false
	}
	return o.HashedPhoneNumber, true
}

// HasHashedPhoneNumber returns a boolean if a field has been set.
func (o *CapiEvent) HasHashedPhoneNumber() bool {
	if o != nil && o.HashedPhoneNumber != nil {
		return true
	}

	return false
}

// SetHashedPhoneNumber gets a reference to the given string and assigns it to the HashedPhoneNumber field.
func (o *CapiEvent) SetHashedPhoneNumber(v string) {
	o.HashedPhoneNumber = &v
}

// GetUserAgent returns the UserAgent field value if set, zero value otherwise.
func (o *CapiEvent) GetUserAgent() string {
	if o == nil || o.UserAgent == nil {
		var ret string
		return ret
	}
	return *o.UserAgent
}

// GetUserAgentOk returns a tuple with the UserAgent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetUserAgentOk() (*string, bool) {
	if o == nil || o.UserAgent == nil {
		return nil, false
	}
	return o.UserAgent, true
}

// HasUserAgent returns a boolean if a field has been set.
func (o *CapiEvent) HasUserAgent() bool {
	if o != nil && o.UserAgent != nil {
		return true
	}

	return false
}

// SetUserAgent gets a reference to the given string and assigns it to the UserAgent field.
func (o *CapiEvent) SetUserAgent(v string) {
	o.UserAgent = &v
}

// GetHashedIpAddress returns the HashedIpAddress field value if set, zero value otherwise.
func (o *CapiEvent) GetHashedIpAddress() string {
	if o == nil || o.HashedIpAddress == nil {
		var ret string
		return ret
	}
	return *o.HashedIpAddress
}

// GetHashedIpAddressOk returns a tuple with the HashedIpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetHashedIpAddressOk() (*string, bool) {
	if o == nil || o.HashedIpAddress == nil {
		return nil, false
	}
	return o.HashedIpAddress, true
}

// HasHashedIpAddress returns a boolean if a field has been set.
func (o *CapiEvent) HasHashedIpAddress() bool {
	if o != nil && o.HashedIpAddress != nil {
		return true
	}

	return false
}

// SetHashedIpAddress gets a reference to the given string and assigns it to the HashedIpAddress field.
func (o *CapiEvent) SetHashedIpAddress(v string) {
	o.HashedIpAddress = &v
}

// GetItemCategory returns the ItemCategory field value if set, zero value otherwise.
func (o *CapiEvent) GetItemCategory() string {
	if o == nil || o.ItemCategory == nil {
		var ret string
		return ret
	}
	return *o.ItemCategory
}

// GetItemCategoryOk returns a tuple with the ItemCategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetItemCategoryOk() (*string, bool) {
	if o == nil || o.ItemCategory == nil {
		return nil, false
	}
	return o.ItemCategory, true
}

// HasItemCategory returns a boolean if a field has been set.
func (o *CapiEvent) HasItemCategory() bool {
	if o != nil && o.ItemCategory != nil {
		return true
	}

	return false
}

// SetItemCategory gets a reference to the given string and assigns it to the ItemCategory field.
func (o *CapiEvent) SetItemCategory(v string) {
	o.ItemCategory = &v
}

// GetItemIds returns the ItemIds field value if set, zero value otherwise.
func (o *CapiEvent) GetItemIds() string {
	if o == nil || o.ItemIds == nil {
		var ret string
		return ret
	}
	return *o.ItemIds
}

// GetItemIdsOk returns a tuple with the ItemIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetItemIdsOk() (*string, bool) {
	if o == nil || o.ItemIds == nil {
		return nil, false
	}
	return o.ItemIds, true
}

// HasItemIds returns a boolean if a field has been set.
func (o *CapiEvent) HasItemIds() bool {
	if o != nil && o.ItemIds != nil {
		return true
	}

	return false
}

// SetItemIds gets a reference to the given string and assigns it to the ItemIds field.
func (o *CapiEvent) SetItemIds(v string) {
	o.ItemIds = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CapiEvent) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CapiEvent) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CapiEvent) SetDescription(v string) {
	o.Description = &v
}

// GetNumberItems returns the NumberItems field value if set, zero value otherwise.
func (o *CapiEvent) GetNumberItems() string {
	if o == nil || o.NumberItems == nil {
		var ret string
		return ret
	}
	return *o.NumberItems
}

// GetNumberItemsOk returns a tuple with the NumberItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetNumberItemsOk() (*string, bool) {
	if o == nil || o.NumberItems == nil {
		return nil, false
	}
	return o.NumberItems, true
}

// HasNumberItems returns a boolean if a field has been set.
func (o *CapiEvent) HasNumberItems() bool {
	if o != nil && o.NumberItems != nil {
		return true
	}

	return false
}

// SetNumberItems gets a reference to the given string and assigns it to the NumberItems field.
func (o *CapiEvent) SetNumberItems(v string) {
	o.NumberItems = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *CapiEvent) GetPrice() string {
	if o == nil || o.Price == nil {
		var ret string
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetPriceOk() (*string, bool) {
	if o == nil || o.Price == nil {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *CapiEvent) HasPrice() bool {
	if o != nil && o.Price != nil {
		return true
	}

	return false
}

// SetPrice gets a reference to the given string and assigns it to the Price field.
func (o *CapiEvent) SetPrice(v string) {
	o.Price = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *CapiEvent) GetCurrency() string {
	if o == nil || o.Currency == nil {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetCurrencyOk() (*string, bool) {
	if o == nil || o.Currency == nil {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *CapiEvent) HasCurrency() bool {
	if o != nil && o.Currency != nil {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *CapiEvent) SetCurrency(v string) {
	o.Currency = &v
}

// GetTransactionId returns the TransactionId field value if set, zero value otherwise.
func (o *CapiEvent) GetTransactionId() string {
	if o == nil || o.TransactionId == nil {
		var ret string
		return ret
	}
	return *o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetTransactionIdOk() (*string, bool) {
	if o == nil || o.TransactionId == nil {
		return nil, false
	}
	return o.TransactionId, true
}

// HasTransactionId returns a boolean if a field has been set.
func (o *CapiEvent) HasTransactionId() bool {
	if o != nil && o.TransactionId != nil {
		return true
	}

	return false
}

// SetTransactionId gets a reference to the given string and assigns it to the TransactionId field.
func (o *CapiEvent) SetTransactionId(v string) {
	o.TransactionId = &v
}

// GetLevel returns the Level field value if set, zero value otherwise.
func (o *CapiEvent) GetLevel() string {
	if o == nil || o.Level == nil {
		var ret string
		return ret
	}
	return *o.Level
}

// GetLevelOk returns a tuple with the Level field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetLevelOk() (*string, bool) {
	if o == nil || o.Level == nil {
		return nil, false
	}
	return o.Level, true
}

// HasLevel returns a boolean if a field has been set.
func (o *CapiEvent) HasLevel() bool {
	if o != nil && o.Level != nil {
		return true
	}

	return false
}

// SetLevel gets a reference to the given string and assigns it to the Level field.
func (o *CapiEvent) SetLevel(v string) {
	o.Level = &v
}

// GetClientDedupId returns the ClientDedupId field value if set, zero value otherwise.
func (o *CapiEvent) GetClientDedupId() string {
	if o == nil || o.ClientDedupId == nil {
		var ret string
		return ret
	}
	return *o.ClientDedupId
}

// GetClientDedupIdOk returns a tuple with the ClientDedupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetClientDedupIdOk() (*string, bool) {
	if o == nil || o.ClientDedupId == nil {
		return nil, false
	}
	return o.ClientDedupId, true
}

// HasClientDedupId returns a boolean if a field has been set.
func (o *CapiEvent) HasClientDedupId() bool {
	if o != nil && o.ClientDedupId != nil {
		return true
	}

	return false
}

// SetClientDedupId gets a reference to the given string and assigns it to the ClientDedupId field.
func (o *CapiEvent) SetClientDedupId(v string) {
	o.ClientDedupId = &v
}

// GetDataUse returns the DataUse field value if set, zero value otherwise.
func (o *CapiEvent) GetDataUse() string {
	if o == nil || o.DataUse == nil {
		var ret string
		return ret
	}
	return *o.DataUse
}

// GetDataUseOk returns a tuple with the DataUse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetDataUseOk() (*string, bool) {
	if o == nil || o.DataUse == nil {
		return nil, false
	}
	return o.DataUse, true
}

// HasDataUse returns a boolean if a field has been set.
func (o *CapiEvent) HasDataUse() bool {
	if o != nil && o.DataUse != nil {
		return true
	}

	return false
}

// SetDataUse gets a reference to the given string and assigns it to the DataUse field.
func (o *CapiEvent) SetDataUse(v string) {
	o.DataUse = &v
}

// GetSearchString returns the SearchString field value if set, zero value otherwise.
func (o *CapiEvent) GetSearchString() string {
	if o == nil || o.SearchString == nil {
		var ret string
		return ret
	}
	return *o.SearchString
}

// GetSearchStringOk returns a tuple with the SearchString field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetSearchStringOk() (*string, bool) {
	if o == nil || o.SearchString == nil {
		return nil, false
	}
	return o.SearchString, true
}

// HasSearchString returns a boolean if a field has been set.
func (o *CapiEvent) HasSearchString() bool {
	if o != nil && o.SearchString != nil {
		return true
	}

	return false
}

// SetSearchString gets a reference to the given string and assigns it to the SearchString field.
func (o *CapiEvent) SetSearchString(v string) {
	o.SearchString = &v
}

// GetPageUrl returns the PageUrl field value if set, zero value otherwise.
func (o *CapiEvent) GetPageUrl() string {
	if o == nil || o.PageUrl == nil {
		var ret string
		return ret
	}
	return *o.PageUrl
}

// GetPageUrlOk returns a tuple with the PageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetPageUrlOk() (*string, bool) {
	if o == nil || o.PageUrl == nil {
		return nil, false
	}
	return o.PageUrl, true
}

// HasPageUrl returns a boolean if a field has been set.
func (o *CapiEvent) HasPageUrl() bool {
	if o != nil && o.PageUrl != nil {
		return true
	}

	return false
}

// SetPageUrl gets a reference to the given string and assigns it to the PageUrl field.
func (o *CapiEvent) SetPageUrl(v string) {
	o.PageUrl = &v
}

// GetSignUpMethod returns the SignUpMethod field value if set, zero value otherwise.
func (o *CapiEvent) GetSignUpMethod() string {
	if o == nil || o.SignUpMethod == nil {
		var ret string
		return ret
	}
	return *o.SignUpMethod
}

// GetSignUpMethodOk returns a tuple with the SignUpMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetSignUpMethodOk() (*string, bool) {
	if o == nil || o.SignUpMethod == nil {
		return nil, false
	}
	return o.SignUpMethod, true
}

// HasSignUpMethod returns a boolean if a field has been set.
func (o *CapiEvent) HasSignUpMethod() bool {
	if o != nil && o.SignUpMethod != nil {
		return true
	}

	return false
}

// SetSignUpMethod gets a reference to the given string and assigns it to the SignUpMethod field.
func (o *CapiEvent) SetSignUpMethod(v string) {
	o.SignUpMethod = &v
}

// GetHashedFirstNameSha returns the HashedFirstNameSha field value if set, zero value otherwise.
func (o *CapiEvent) GetHashedFirstNameSha() string {
	if o == nil || o.HashedFirstNameSha == nil {
		var ret string
		return ret
	}
	return *o.HashedFirstNameSha
}

// GetHashedFirstNameShaOk returns a tuple with the HashedFirstNameSha field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetHashedFirstNameShaOk() (*string, bool) {
	if o == nil || o.HashedFirstNameSha == nil {
		return nil, false
	}
	return o.HashedFirstNameSha, true
}

// HasHashedFirstNameSha returns a boolean if a field has been set.
func (o *CapiEvent) HasHashedFirstNameSha() bool {
	if o != nil && o.HashedFirstNameSha != nil {
		return true
	}

	return false
}

// SetHashedFirstNameSha gets a reference to the given string and assigns it to the HashedFirstNameSha field.
func (o *CapiEvent) SetHashedFirstNameSha(v string) {
	o.HashedFirstNameSha = &v
}

// GetHashedFirstNameSdx returns the HashedFirstNameSdx field value if set, zero value otherwise.
func (o *CapiEvent) GetHashedFirstNameSdx() string {
	if o == nil || o.HashedFirstNameSdx == nil {
		var ret string
		return ret
	}
	return *o.HashedFirstNameSdx
}

// GetHashedFirstNameSdxOk returns a tuple with the HashedFirstNameSdx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetHashedFirstNameSdxOk() (*string, bool) {
	if o == nil || o.HashedFirstNameSdx == nil {
		return nil, false
	}
	return o.HashedFirstNameSdx, true
}

// HasHashedFirstNameSdx returns a boolean if a field has been set.
func (o *CapiEvent) HasHashedFirstNameSdx() bool {
	if o != nil && o.HashedFirstNameSdx != nil {
		return true
	}

	return false
}

// SetHashedFirstNameSdx gets a reference to the given string and assigns it to the HashedFirstNameSdx field.
func (o *CapiEvent) SetHashedFirstNameSdx(v string) {
	o.HashedFirstNameSdx = &v
}

// GetHashedMiddleNameSha returns the HashedMiddleNameSha field value if set, zero value otherwise.
func (o *CapiEvent) GetHashedMiddleNameSha() string {
	if o == nil || o.HashedMiddleNameSha == nil {
		var ret string
		return ret
	}
	return *o.HashedMiddleNameSha
}

// GetHashedMiddleNameShaOk returns a tuple with the HashedMiddleNameSha field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetHashedMiddleNameShaOk() (*string, bool) {
	if o == nil || o.HashedMiddleNameSha == nil {
		return nil, false
	}
	return o.HashedMiddleNameSha, true
}

// HasHashedMiddleNameSha returns a boolean if a field has been set.
func (o *CapiEvent) HasHashedMiddleNameSha() bool {
	if o != nil && o.HashedMiddleNameSha != nil {
		return true
	}

	return false
}

// SetHashedMiddleNameSha gets a reference to the given string and assigns it to the HashedMiddleNameSha field.
func (o *CapiEvent) SetHashedMiddleNameSha(v string) {
	o.HashedMiddleNameSha = &v
}

// GetHashedMiddleNameSdx returns the HashedMiddleNameSdx field value if set, zero value otherwise.
func (o *CapiEvent) GetHashedMiddleNameSdx() string {
	if o == nil || o.HashedMiddleNameSdx == nil {
		var ret string
		return ret
	}
	return *o.HashedMiddleNameSdx
}

// GetHashedMiddleNameSdxOk returns a tuple with the HashedMiddleNameSdx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetHashedMiddleNameSdxOk() (*string, bool) {
	if o == nil || o.HashedMiddleNameSdx == nil {
		return nil, false
	}
	return o.HashedMiddleNameSdx, true
}

// HasHashedMiddleNameSdx returns a boolean if a field has been set.
func (o *CapiEvent) HasHashedMiddleNameSdx() bool {
	if o != nil && o.HashedMiddleNameSdx != nil {
		return true
	}

	return false
}

// SetHashedMiddleNameSdx gets a reference to the given string and assigns it to the HashedMiddleNameSdx field.
func (o *CapiEvent) SetHashedMiddleNameSdx(v string) {
	o.HashedMiddleNameSdx = &v
}

// GetHashedLastNameSha returns the HashedLastNameSha field value if set, zero value otherwise.
func (o *CapiEvent) GetHashedLastNameSha() string {
	if o == nil || o.HashedLastNameSha == nil {
		var ret string
		return ret
	}
	return *o.HashedLastNameSha
}

// GetHashedLastNameShaOk returns a tuple with the HashedLastNameSha field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetHashedLastNameShaOk() (*string, bool) {
	if o == nil || o.HashedLastNameSha == nil {
		return nil, false
	}
	return o.HashedLastNameSha, true
}

// HasHashedLastNameSha returns a boolean if a field has been set.
func (o *CapiEvent) HasHashedLastNameSha() bool {
	if o != nil && o.HashedLastNameSha != nil {
		return true
	}

	return false
}

// SetHashedLastNameSha gets a reference to the given string and assigns it to the HashedLastNameSha field.
func (o *CapiEvent) SetHashedLastNameSha(v string) {
	o.HashedLastNameSha = &v
}

// GetHashedLastNameSdx returns the HashedLastNameSdx field value if set, zero value otherwise.
func (o *CapiEvent) GetHashedLastNameSdx() string {
	if o == nil || o.HashedLastNameSdx == nil {
		var ret string
		return ret
	}
	return *o.HashedLastNameSdx
}

// GetHashedLastNameSdxOk returns a tuple with the HashedLastNameSdx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetHashedLastNameSdxOk() (*string, bool) {
	if o == nil || o.HashedLastNameSdx == nil {
		return nil, false
	}
	return o.HashedLastNameSdx, true
}

// HasHashedLastNameSdx returns a boolean if a field has been set.
func (o *CapiEvent) HasHashedLastNameSdx() bool {
	if o != nil && o.HashedLastNameSdx != nil {
		return true
	}

	return false
}

// SetHashedLastNameSdx gets a reference to the given string and assigns it to the HashedLastNameSdx field.
func (o *CapiEvent) SetHashedLastNameSdx(v string) {
	o.HashedLastNameSdx = &v
}

// GetHashedCitySha returns the HashedCitySha field value if set, zero value otherwise.
func (o *CapiEvent) GetHashedCitySha() string {
	if o == nil || o.HashedCitySha == nil {
		var ret string
		return ret
	}
	return *o.HashedCitySha
}

// GetHashedCityShaOk returns a tuple with the HashedCitySha field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetHashedCityShaOk() (*string, bool) {
	if o == nil || o.HashedCitySha == nil {
		return nil, false
	}
	return o.HashedCitySha, true
}

// HasHashedCitySha returns a boolean if a field has been set.
func (o *CapiEvent) HasHashedCitySha() bool {
	if o != nil && o.HashedCitySha != nil {
		return true
	}

	return false
}

// SetHashedCitySha gets a reference to the given string and assigns it to the HashedCitySha field.
func (o *CapiEvent) SetHashedCitySha(v string) {
	o.HashedCitySha = &v
}

// GetHashedCitySdx returns the HashedCitySdx field value if set, zero value otherwise.
func (o *CapiEvent) GetHashedCitySdx() string {
	if o == nil || o.HashedCitySdx == nil {
		var ret string
		return ret
	}
	return *o.HashedCitySdx
}

// GetHashedCitySdxOk returns a tuple with the HashedCitySdx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetHashedCitySdxOk() (*string, bool) {
	if o == nil || o.HashedCitySdx == nil {
		return nil, false
	}
	return o.HashedCitySdx, true
}

// HasHashedCitySdx returns a boolean if a field has been set.
func (o *CapiEvent) HasHashedCitySdx() bool {
	if o != nil && o.HashedCitySdx != nil {
		return true
	}

	return false
}

// SetHashedCitySdx gets a reference to the given string and assigns it to the HashedCitySdx field.
func (o *CapiEvent) SetHashedCitySdx(v string) {
	o.HashedCitySdx = &v
}

// GetHashedStateSha returns the HashedStateSha field value if set, zero value otherwise.
func (o *CapiEvent) GetHashedStateSha() string {
	if o == nil || o.HashedStateSha == nil {
		var ret string
		return ret
	}
	return *o.HashedStateSha
}

// GetHashedStateShaOk returns a tuple with the HashedStateSha field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetHashedStateShaOk() (*string, bool) {
	if o == nil || o.HashedStateSha == nil {
		return nil, false
	}
	return o.HashedStateSha, true
}

// HasHashedStateSha returns a boolean if a field has been set.
func (o *CapiEvent) HasHashedStateSha() bool {
	if o != nil && o.HashedStateSha != nil {
		return true
	}

	return false
}

// SetHashedStateSha gets a reference to the given string and assigns it to the HashedStateSha field.
func (o *CapiEvent) SetHashedStateSha(v string) {
	o.HashedStateSha = &v
}

// GetHashedStateSdx returns the HashedStateSdx field value if set, zero value otherwise.
func (o *CapiEvent) GetHashedStateSdx() string {
	if o == nil || o.HashedStateSdx == nil {
		var ret string
		return ret
	}
	return *o.HashedStateSdx
}

// GetHashedStateSdxOk returns a tuple with the HashedStateSdx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetHashedStateSdxOk() (*string, bool) {
	if o == nil || o.HashedStateSdx == nil {
		return nil, false
	}
	return o.HashedStateSdx, true
}

// HasHashedStateSdx returns a boolean if a field has been set.
func (o *CapiEvent) HasHashedStateSdx() bool {
	if o != nil && o.HashedStateSdx != nil {
		return true
	}

	return false
}

// SetHashedStateSdx gets a reference to the given string and assigns it to the HashedStateSdx field.
func (o *CapiEvent) SetHashedStateSdx(v string) {
	o.HashedStateSdx = &v
}

// GetHashedZip returns the HashedZip field value if set, zero value otherwise.
func (o *CapiEvent) GetHashedZip() string {
	if o == nil || o.HashedZip == nil {
		var ret string
		return ret
	}
	return *o.HashedZip
}

// GetHashedZipOk returns a tuple with the HashedZip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetHashedZipOk() (*string, bool) {
	if o == nil || o.HashedZip == nil {
		return nil, false
	}
	return o.HashedZip, true
}

// HasHashedZip returns a boolean if a field has been set.
func (o *CapiEvent) HasHashedZip() bool {
	if o != nil && o.HashedZip != nil {
		return true
	}

	return false
}

// SetHashedZip gets a reference to the given string and assigns it to the HashedZip field.
func (o *CapiEvent) SetHashedZip(v string) {
	o.HashedZip = &v
}

// GetHashedDobMonth returns the HashedDobMonth field value if set, zero value otherwise.
func (o *CapiEvent) GetHashedDobMonth() string {
	if o == nil || o.HashedDobMonth == nil {
		var ret string
		return ret
	}
	return *o.HashedDobMonth
}

// GetHashedDobMonthOk returns a tuple with the HashedDobMonth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetHashedDobMonthOk() (*string, bool) {
	if o == nil || o.HashedDobMonth == nil {
		return nil, false
	}
	return o.HashedDobMonth, true
}

// HasHashedDobMonth returns a boolean if a field has been set.
func (o *CapiEvent) HasHashedDobMonth() bool {
	if o != nil && o.HashedDobMonth != nil {
		return true
	}

	return false
}

// SetHashedDobMonth gets a reference to the given string and assigns it to the HashedDobMonth field.
func (o *CapiEvent) SetHashedDobMonth(v string) {
	o.HashedDobMonth = &v
}

// GetHashedDobDay returns the HashedDobDay field value if set, zero value otherwise.
func (o *CapiEvent) GetHashedDobDay() string {
	if o == nil || o.HashedDobDay == nil {
		var ret string
		return ret
	}
	return *o.HashedDobDay
}

// GetHashedDobDayOk returns a tuple with the HashedDobDay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetHashedDobDayOk() (*string, bool) {
	if o == nil || o.HashedDobDay == nil {
		return nil, false
	}
	return o.HashedDobDay, true
}

// HasHashedDobDay returns a boolean if a field has been set.
func (o *CapiEvent) HasHashedDobDay() bool {
	if o != nil && o.HashedDobDay != nil {
		return true
	}

	return false
}

// SetHashedDobDay gets a reference to the given string and assigns it to the HashedDobDay field.
func (o *CapiEvent) SetHashedDobDay(v string) {
	o.HashedDobDay = &v
}

// GetIntegration returns the Integration field value if set, zero value otherwise.
func (o *CapiEvent) GetIntegration() string {
	if o == nil || o.Integration == nil {
		var ret string
		return ret
	}
	return *o.Integration
}

// GetIntegrationOk returns a tuple with the Integration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetIntegrationOk() (*string, bool) {
	if o == nil || o.Integration == nil {
		return nil, false
	}
	return o.Integration, true
}

// HasIntegration returns a boolean if a field has been set.
func (o *CapiEvent) HasIntegration() bool {
	if o != nil && o.Integration != nil {
		return true
	}

	return false
}

// SetIntegration gets a reference to the given string and assigns it to the Integration field.
func (o *CapiEvent) SetIntegration(v string) {
	o.Integration = &v
}

// GetClickId returns the ClickId field value if set, zero value otherwise.
func (o *CapiEvent) GetClickId() string {
	if o == nil || o.ClickId == nil {
		var ret string
		return ret
	}
	return *o.ClickId
}

// GetClickIdOk returns a tuple with the ClickId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapiEvent) GetClickIdOk() (*string, bool) {
	if o == nil || o.ClickId == nil {
		return nil, false
	}
	return o.ClickId, true
}

// HasClickId returns a boolean if a field has been set.
func (o *CapiEvent) HasClickId() bool {
	if o != nil && o.ClickId != nil {
		return true
	}

	return false
}

// SetClickId gets a reference to the given string and assigns it to the ClickId field.
func (o *CapiEvent) SetClickId(v string) {
	o.ClickId = &v
}

func (o CapiEvent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.PixelId != nil {
		toSerialize["pixel_id"] = o.PixelId
	}
	if o.AppId != nil {
		toSerialize["app_id"] = o.AppId
	}
	if o.SnapAppId != nil {
		toSerialize["snap_app_id"] = o.SnapAppId
	}
	if o.EventType != nil {
		toSerialize["event_type"] = o.EventType
	}
	if o.EventConversionType != nil {
		toSerialize["event_conversion_type"] = o.EventConversionType
	}
	if o.EventTag != nil {
		toSerialize["event_tag"] = o.EventTag
	}
	if o.Timestamp != nil {
		toSerialize["timestamp"] = o.Timestamp
	}
	if o.HashedEmail != nil {
		toSerialize["hashed_email"] = o.HashedEmail
	}
	if o.HashedMobileAdId != nil {
		toSerialize["hashed_mobile_ad_id"] = o.HashedMobileAdId
	}
	if o.UuidC1 != nil {
		toSerialize["uuid_c1"] = o.UuidC1
	}
	if o.HashedIdfv != nil {
		toSerialize["hashed_idfv"] = o.HashedIdfv
	}
	if o.HashedPhoneNumber != nil {
		toSerialize["hashed_phone_number"] = o.HashedPhoneNumber
	}
	if o.UserAgent != nil {
		toSerialize["user_agent"] = o.UserAgent
	}
	if o.HashedIpAddress != nil {
		toSerialize["hashed_ip_address"] = o.HashedIpAddress
	}
	if o.ItemCategory != nil {
		toSerialize["item_category"] = o.ItemCategory
	}
	if o.ItemIds != nil {
		toSerialize["item_ids"] = o.ItemIds
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.NumberItems != nil {
		toSerialize["number_items"] = o.NumberItems
	}
	if o.Price != nil {
		toSerialize["price"] = o.Price
	}
	if o.Currency != nil {
		toSerialize["currency"] = o.Currency
	}
	if o.TransactionId != nil {
		toSerialize["transaction_id"] = o.TransactionId
	}
	if o.Level != nil {
		toSerialize["level"] = o.Level
	}
	if o.ClientDedupId != nil {
		toSerialize["client_dedup_id"] = o.ClientDedupId
	}
	if o.DataUse != nil {
		toSerialize["data_use"] = o.DataUse
	}
	if o.SearchString != nil {
		toSerialize["search_string"] = o.SearchString
	}
	if o.PageUrl != nil {
		toSerialize["page_url"] = o.PageUrl
	}
	if o.SignUpMethod != nil {
		toSerialize["sign_up_method"] = o.SignUpMethod
	}
	if o.HashedFirstNameSha != nil {
		toSerialize["hashed_first_name_sha"] = o.HashedFirstNameSha
	}
	if o.HashedFirstNameSdx != nil {
		toSerialize["hashed_first_name_sdx"] = o.HashedFirstNameSdx
	}
	if o.HashedMiddleNameSha != nil {
		toSerialize["hashed_middle_name_sha"] = o.HashedMiddleNameSha
	}
	if o.HashedMiddleNameSdx != nil {
		toSerialize["hashed_middle_name_sdx"] = o.HashedMiddleNameSdx
	}
	if o.HashedLastNameSha != nil {
		toSerialize["hashed_last_name_sha"] = o.HashedLastNameSha
	}
	if o.HashedLastNameSdx != nil {
		toSerialize["hashed_last_name_sdx"] = o.HashedLastNameSdx
	}
	if o.HashedCitySha != nil {
		toSerialize["hashed_city_sha"] = o.HashedCitySha
	}
	if o.HashedCitySdx != nil {
		toSerialize["hashed_city_sdx"] = o.HashedCitySdx
	}
	if o.HashedStateSha != nil {
		toSerialize["hashed_state_sha"] = o.HashedStateSha
	}
	if o.HashedStateSdx != nil {
		toSerialize["hashed_state_sdx"] = o.HashedStateSdx
	}
	if o.HashedZip != nil {
		toSerialize["hashed_zip"] = o.HashedZip
	}
	if o.HashedDobMonth != nil {
		toSerialize["hashed_dob_month"] = o.HashedDobMonth
	}
	if o.HashedDobDay != nil {
		toSerialize["hashed_dob_day"] = o.HashedDobDay
	}
	if o.Integration != nil {
		toSerialize["integration"] = o.Integration
	}
	if o.ClickId != nil {
		toSerialize["click_id"] = o.ClickId
	}
	return json.Marshal(toSerialize)
}

type NullableCapiEvent struct {
	value *CapiEvent
	isSet bool
}

func (v NullableCapiEvent) Get() *CapiEvent {
	return v.value
}

func (v *NullableCapiEvent) Set(val *CapiEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableCapiEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableCapiEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCapiEvent(val *CapiEvent) *NullableCapiEvent {
	return &NullableCapiEvent{value: val, isSet: true}
}

func (v NullableCapiEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCapiEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


